name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            archive: tar.gz
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            archive: tar.gz
            use_cross: true
          - target: x86_64-apple-darwin
            os: macos-latest
            archive: tar.gz
          - target: aarch64-apple-darwin
            os: macos-latest
            archive: tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            archive: zip

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross
      if: matrix.use_cross
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build with cross
      if: matrix.use_cross
      run: cross build --release --target ${{ matrix.target }}

    - name: Build with cargo
      if: "!matrix.use_cross"
      run: cargo build --release --target ${{ matrix.target }}

    - name: Create archive (Unix)
      if: matrix.archive == 'tar.gz'
      run: |
        cd target/${{ matrix.target }}/release
        tar -czf ../../../asmodeus-lsp-${{ github.ref_name }}-${{ matrix.target }}.tar.gz asmodeus-lsp
        cd ../../../

    - name: Create archive (Windows)
      if: matrix.archive == 'zip'
      run: |
        cd target/${{ matrix.target }}/release
        7z a ../../../asmodeus-lsp-${{ github.ref_name }}-${{ matrix.target }}.zip asmodeus-lsp.exe
        cd ../../../

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: asmodeus-lsp-${{ matrix.target }}
        path: asmodeus-lsp-${{ github.ref_name }}-${{ matrix.target }}.*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: Display structure of downloaded files
      run: ls -la

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          asmodeus-lsp-x86_64-unknown-linux-gnu/asmodeus-lsp-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
          asmodeus-lsp-aarch64-unknown-linux-gnu/asmodeus-lsp-${{ github.ref_name }}-aarch64-unknown-linux-gnu.tar.gz
          asmodeus-lsp-x86_64-apple-darwin/asmodeus-lsp-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz
          asmodeus-lsp-aarch64-apple-darwin/asmodeus-lsp-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz
          asmodeus-lsp-x86_64-pc-windows-msvc/asmodeus-lsp-${{ github.ref_name }}-x86_64-pc-windows-msvc.zip
        generate_release_notes: true
        draft: false
        prerelease: false
        make_latest: true
